---
- hosts: all
  sudo: yes

  vars:
    downloads_directory: "{{ ansible_env.HOME }}/downloads"
  vars_files:
    - variables.yml

  roles:
    - init
    - jdk
    - git
    - scala
    - spark
    - python_tools
