---
- hosts: all
  sudo: yes

  vars:
    downloads_directory: "{{ ansible_env.HOME}}/downloads"
    scala:
      download_url: http://downloads.lightbend.com/scala/2.10.6/scala-2.10.6.tgz
      install_directory: /usr/local/scala
      bin_directory: /usr/local/scala/bin
    spark:
      download_url: http://d3kbcqa49mib13.cloudfront.net/spark-1.6.1-bin-hadoop2.6.tgz
      install_directory: /usr/local/spark
      bin_directory: /usr/local/spark/bin

  tasks:
    - name: Update server
      apt: update_cache=yes
    - name: Install Java 7 JDK
      apt: name=openjdk-7-jre-headless state=present

    - name: Create downloads directory
      file: state=directory path={{ downloads_directory }}

    - name: Download Scala 2.10.6
      get_url: url={{ scala.download_url }} dest={{ downloads_directory }}
    - name: Extract Scala 2.10.6
      unarchive: src={{ downloads_directory }}/scala-2.10.6.tgz dest={{ downloads_directory }} copy=no
    - name: Move Scala to install directory
      command: mv {{ downloads_directory }}/scala-2.10.6 {{ scala.install_directory }}
    - name: "add {{ scala.bin_directory }} to PATH"
      lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?{{scala.bin_directory}}).*?)(["]*)$' line="PATH=\1\2:{{ scala.bin_directory }}\3"

    - name: Download Spark 1.6.1
      get_url: url={{ spark.download_url }} dest={{ downloads_directory }}
    - name: Extract Spark 1.6.1
      unarchive: src={{ downloads_directory }}/spark-1.6.1-bin-hadoop2.6.tgz dest={{ downloads_directory }} copy=no
    - name: Move Spark to install directory
      command: mv {{ downloads_directory }}/spark-1.6.1-bin-hadoop2.6 {{ spark.install_directory }}
    - name: "add {{ spark.bin_directory }} to PATH"
      lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?{{spark.bin_directory}}).*?)(["]*)$' line="PATH=\1\2:{{ spark.bin_directory }}\3"

    - name: Install pip
      apt: name={{item}} state=installed
      with_items:
        - python-pip
        - python-dev
        - build-essential
    - name: Install pytest
      pip: name=pytest
    - name: Install find findspark
      pip: name=findspark
    - name: Install boto3
      pip: name=boto3
