---
- hosts: all
  sudo: yes

  vars:
    downloads_directory: "{{ ansible_env.HOME }}/downloads"
    scala:
      version: 2.11.8
    spark:
      version: 1.6.3
    hadoop:
      version: 2.6

  roles:
    - init
    - jdk
    - git
    - scala
    - spark
    - python_tools
